### ISSUE TITLE
UI crash when adding ccBNB && ccETC liquidity

### ISSUE THREAD

**Issue by Manglobite** [SoyFinance/Soy.Finance#1]
case

- open https://app.soy.finance/
- go to Trade - liquidity
- add liquidity
- chose ccBNB + ccETC
![image](https://user-images.githubusercontent.com/49619706/140023582-3c130d2b-e4b3-4b8c-9cfa-65c1b9bcf60f.png)

- tap max in ccETC

getted white sreen with errors in console
![image](https://user-images.githubusercontent.com/49619706/140023738-71d844b3-6c68-4ec6-847c-2aa0b489f70e.png)
Windows 11 - Chrome 95.0.4638.69 

ccETH balance == 0.000000000000000001 float overflow?

**Comment by MufCZ** [comment]
This repo is for https://soy.finance/ not https://app.soy.finance/
